apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: hpaapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hpaapi
  template:
    metadata:
      labels:
        app: hpaapi
    spec:
      containers:
        - name: hpaapi
          image: vigneshwar11/hpaexample:v3
          resources:
              requests:
                  memory: "150M"
                  cpu: "20m"
              limits:
                  memory: "500M"

          ports:
            - containerPort: 80
              name: hpa-api
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '80'
spec:
  type: LoadBalancer
  selector:
    app: hpaapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: hpa-api
      nodePort: 30210

