apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: api-deployment
  minReplicaCount: 2   #Optional Default 0
  maxReplicaCount: 4  #Optional Default 100
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://10.96.105.40:80 # verify this is correct
      metricName: hpaexample_Largecart_Number # DEPRECATED: This parameter is deprecated as of KEDA v2.10 and will be removed in version 2.12
      threshold: "0.1"
      #query: histogram_quantile(0.90, rate(http_request_duration_seconds_bucket[2m]))
      query: sum(rate(hpaexample_Largecart_Number[5m]))
